name: php-upn-qr-generator
services:
  appserver:
    type: php:custom
    via: cli
    overrides:
      image: slimdeluxe/php:7.4
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
