name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 7.4, 8.0, 8.1 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: ${{ matrix.os }} / PHP ${{ matrix.php }} / ${{ matrix.dependency-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, iconv, imagick

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --${{ matrix.dependency-version }}

    - name: Run test suite
      run: composer test
